// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    Circle: typeof import('~icons/ci/rcle')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    MdiAlien: typeof import('~icons/mdi/alien')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    OnepisyaBiSunrise: typeof import('~icons/bi/sunrise')['default']
    OnepisyaBiSunRise: typeof import('~icons/bi/sun-rise')['default']
    OnepisyaEpRise: typeof import('~icons/ep/rise')['default']
    OnepisyaEpSu: typeof import('~icons/ep/su')['default']
    OnepisyaEpSun: typeof import('~icons/ep/sun')['default']
    OnepisyaEpSunny: typeof import('~icons/ep/sunny')['default']
    OnepisyaEpSunrise: typeof import('~icons/ep/sunrise')['default']
    OnepisyaEpSunRise: typeof import('~icons/ep/sun-rise')['default']
    OnepisyaEpSurise: typeof import('~icons/ep/surise')['default']
    OnepisyaEpWbSunny: typeof import('~icons/ep/wb-sunny')['default']
    OnepisyaMaterialSymbolsWbSunny: typeof import('~icons/material-symbols/wb-sunny')['default']
    OnepisyaMdiAlien: typeof import('~icons/mdi/alien')['default']
    OnepisyaMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    OnepisyaMdiGithub: typeof import('~icons/mdi/github')['default']
    OnepisyaMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    OnepisyaMdiSunny: typeof import('~icons/mdi/sunny')['default']
    OnepisyaMdiSuny: typeof import('~icons/mdi/suny')['default']
    OnepisyaMdiWbSunny: typeof import('~icons/mdi/wb-sunny')['default']
    OnepisyaMdiWbSunnyRounded: typeof import('~icons/mdi/wb-sunny-rounded')['default']
    OnepisyaMdiWbSuny: typeof import('~icons/mdi/wb-suny')['default']
    OnepisyaMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    OnepisyaMdiWheatherSunny: typeof import('~icons/mdi/wheather-sunny')['default']
    OnepisyaMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestAxios: typeof import('./components/test/TestAxios.vue')['default']
    TestD3: typeof import('./components/test/TestD3.vue')['default']
    TestMqtt: typeof import('./components/test/TestMqtt.vue')['default']
    TestPinia: typeof import('./components/test/TestPinia.vue')['default']
    TestTailWindVueCom: typeof import('./components/test/TestTailWindVueCom.vue')['default']
  }
}
